name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Build
        run: go build ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Setup SSH
        env:
          SERVER_HOST: ${{ vars.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.OVH_VPS_1 }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          printf '%s\n' "$SERVER_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh -o BatchMode=yes gha@"$SERVER_HOST" \
            "sudo -u almalinux /opt/menflubot/deploy.sh"
